### ISSUE TITLE
New reqt: White narrative

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#13]
The clients checked if it would be possible to record a White (umpire's) narrative.

This would include formal statements related to game-play like:
`given the already poor state of HMS Gavin, hitting a sea-mount has resulted in her being sunk`

Or just a White-only chat room, with:
`can someone come down and cover room 12 for 10 minutes? (comfort break)`

I confirmed that yes, this could be met with a channel that was for White roles only.  It may just have a `General` message type.  But, maybe an `Umpire Statement` message type would ensure all of the formal statements were collected together, and retrievable.

**Comment by clenoble** [comment]
To unpack the information in this feedback: 
- white is a color dedicated to umpire (so can't be chosen for a player force): is it by default, or could the game designer change this?
- Will the formal statements also be Umpire-only or accessible to all players? 
- Having different message types with exactly the same fields will likely result in confusion and errors: when should I use this one or that one? The examples you mention are clear cut, but there might be circumstances where the difference is more difficult to sort out. If we keep both types of messages in the same channel, then the generic message type could allow the users to add some tags or categories. This would make them retrievable and searchable, but would be less prone to errors. 
If there is a clear difference between the 2 types of messages, maybe they could be in 2 different channels. I'm thinking of Observers and VIP, who will have access to everything. They will be interested in formal statements, but not in umpire logistic types of messages.

**Comment by IanMayo** [comment]
@clenoble - that's all good.

1. **White** force.  Yes, `White Cell` refers to the umpires of the game.  Note: there remains room for confusion here. This morning a game designer indicated that one force may represent "White Shipping".  `White` in this context means non-military commercial shipping.  The designer originally called this the `White cell`, but quickly corrected his phrase to `Green Shipping` in the `Green Cell`.  Within this color-based perspective on national loyalties, `Green` traditionally refers to `friendly` - so quickly changing `White` to `Green` is quite acceptable.   But, as I said - there remains room for confusion here in the future.
2. **Formal statements**.  These won't be made visible to all players.  Aah, except in a post-wargame debrief, where the players view the _gods-eye_ view of what happened during the wargame. [1].
3. **Message Types**.  I think having message types is important for their post-event analysis, and ensuring there isn't an overlap between the message types is an important responsibility of the Game Designer.  By having separate message-types, it's possible for an analyst to request to see all the machinery failures, the diplomatic cables, missile launch requests, etc.    Even though each of the above may be represented as a free-text block, knowing the type allows them to be quickly filtered.   This morning the designers agreed that it was to their benefit to pull as much metadata as possible out of the text box - into numbers or drop-down lists, since that will help both short term analysis, and the improved automation of the umpire role in the longer term.

Yes, it would be logical for the game designers to plan one White Chat room for high level formal statements, and another for internal admin.


[1]. That's a something I don't think we've captured as a requirement - the need to perform debriefs. These may be conducted at the end of a real-day - where the participants view what happened in the last game-week, and get chance to refine their strategies before replaying the game again tomorrow.  Or, at the end of real-week, they may get debriefed on the last game-month, viewing near-misses, successes, mistakes, etc.

**Comment by clenoble** [comment]
Analysis and debriefing would be an entirely different UI, with as you mention, a search interface based on message types, time, forces (tags or categories possibly), or free text search. Analysts should be able to take / make snapshots of a particular moment possibly, or pull together a series of moves and / or messages. 
This could be an extension of the observer role, which for now has only the possibility to take notes.

**Comment by IanMayo** [comment]
Well, analysis and debriefing would be two different UIs :-)

For analysis they need to be able to search and filter the data in any way they like.

But, for debriefing there would just be a time slider control (or play/pause buttons), with the person giving the debrief able to control time and to manually zoom/pan around the map control.  The person doing the debriefing may wish to have one or more message channels open, if the messages relate to what is being debriefed.

**Comment by IanMayo** [comment]
Closing this. As the client's understanding has matured, they're grown more used to lots and lots of plain chat-rooms.
