### ISSUE TITLE
PMESSI scale

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#14]
A client introduced me to the PMESSI scale.  It is represented by 1-10 scores for each of a series of characteristics:
![image](https://user-images.githubusercontent.com/1108513/54608261-465b4c80-4a48-11e9-9636-a2dc0ad10257.png)

He asked if it would eventually be possible to allow these scores to be collected and displayed within the app.

I explained that yes - in the near term the data could be collected via a custom message type. That message type would be defined as a series of named 1-10 range sliders.   The same sliders would display the results when the message was received.

In the longer term, the same structured message could be met through a dedicated editor form for that message type, and the results potentially displayed at the foot of the `Game Control` window for that force.

**Comment by clenoble** [comment]
Having a separate message type just for this scale might make it difficult to associate these numbers and what they are measuring, which will be described in another message.
Maybe this scale could be attached to existing types of messages like daily intentions or state of the world, or even as properties of a specific field in a message (as they relate to the consequences of an action).

**Comment by IanMayo** [comment]
Yes, these details could be added to an existing message format.

It's a useful example of a type of message that relates to a whole Force/Cell, but not to an individual platform.

It's also an example of where it could start with a `dumb` editor that our message-type designer UI produces, but later be replaced with a dedicated custom editor that follows the color conventions for the assorted scales, plus potenitally an overall score for that force.

I've just had a quick go at producing such an editor with our message-type designer.  Here's an example (excuse the really long URL, it's because all the data is in there too).

https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoACkgDbkWYCGjt40ciVYhcgDsA5nhAAzJIQC2bHIkJtRcfDOHkZAVxkIAjGrYAPTTv0AGfABMYEtlsYKArNeqZBUCkiEIQDZqwcAASaUGzYQUgSQWBIVmwQAORUQTAAbjBCYDQAvvgAsuQBbIQQXJCwvvyCouJSsvK+Siri6kKmuvAGIHIm2p16liA2dg7OrlTu5J7k3r6FxaUhMmERUTFxCcmpGVm5+ACimN5I6pjlPFUCwmL49XIKIM0iqj0a/fqGfWZdQyP2jgQLmGbg8Xh8iCOJzOy1WYEi0Vi8SSKXSmWyIDyIAAykhMOQOBdKnxrrU7tIHk1lC9Wu8ft1eh0LK5RoD4MCbJMwbMITi8QTGLDwvD1kitqjdhiclj7o1ECJBFZxBQwIxeH4DtjsfkAJJBbHHQivI0ARy05CNSvgAG0/EwWOR2JwCkUWCUyodjkJTo7xLj8YSALo5IA===&value=N4IgCg9gNglgLjAxgQyiAXCArCANCAWRljmQCcBPDEAdjxAFFEIA7CAWyWp3wGUJEMVNxABfIA==&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by IanMayo** [comment]
This requirement has not been mentioned since the original conversation.  Defer until we get more SME interest.
