### ISSUE TITLE
Planning has to handle Groups and Platforms

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#15]
In the player planning step the will provide the movement for each group.  But, they will provide the platform instructions for each platform within that group.  The platform instructions may be pre-populated with those provided for the previous step, to reduce re-typing.

So, the daily intentions happen at two levels
* route information for the whole group
* intentions for each platform (according to the characteristics of that platform-type, as provided by the game designer).

The same split _may_ also happen in the execution cycle: the umpires may provide the routing for the whole group, but also give a description of the state for each platform - potentially including fuel remaining, weapons remaining, etc.

**Comment by clenoble** [comment]
This means that the format editor should allow the user to specify when a property is inherited by default from the parent field. Or is it part of the templates we would provide them and possibly code manually?

**Comment by IanMayo** [comment]
I haven't planned the detail of this yet, but....

It's my intention that each time a "State of the World" message goes from the Umpires down to the Players, it will have an attachment. That attachment is a default version of the "Daily intentions" message that the players will be completing.  So, as the planning cycle starts, the system will open that attachment - and start editing from there.

Default state (maintaining the status quo) will be by not making any changes to the Daily Intentions message.  But, to change the posture of a platform (passive to aggressive) they edit a drop-down for that platform.

(We talked this through this morning)

The `Daily Intentions` message remains just that - intentions.  It's asking that platform to do those things in the next day.  It's during the execution cycle that the real world steps in.  So, while the player told a platform to be really aggressive for the next 24 hours...  It may get hit by a missile right at the start of execution, and the umpires decide it's actually going to be really evasive.  So, when the "State of the World" message goes from Umpires back to Blue - that's when the players learn what's happened.

**Comment by IanMayo** [comment]
Closed - sorted.
