### ISSUE TITLE
Platform Characteristics apply separately for Planning & Execution

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#16]
Our Game Design UI acknowledges that the Game Designer will provide a description of the characteristics for that platform type.

But, it actually sits in two forms:  the planning message must contain the fields necessary to instruct the that platform what to do in the next cycle.  The execution message must contain the fields that record the actual state of that platform (maybe including a summary of what that platform did, fuel remaining, weapons remaining, details on any movement (speed) constraints.

**Comment by clenoble** [comment]
- In the form editor, the game designer should be able to select specific characteristics from a platform, rather than all platform characteristics being added to each form.

**Comment by IanMayo** [comment]
That wasn't quite my intention.

I intended to say that I believe we need two sets of platform characteristics for each platform type.  One set get filled in by the Players at the end of the planning phase.  These are the **specific instructions for that platform type**.  So, for a helicopter there could be a drop-down menu with a number of search patterns (Ladder, Spiral, Barrier, Ellipse).  But, for a Warship it could include the radar state (on or off).

The other set get filled in by the Umpires at the end of the execution phase.  Again these are specific to each platform type, and give a **factual status of the condition of that platform type**.  A helicopter could include fuel level, number of remaining missiles.  For a Warship it could include number of days of food remaining, the motivation level of the crew, fuel (again).

**Comment by clenoble** [comment]
The platform characteristics are not defined in the message directly, but in the platform types. All characteristics (filled either by umpires or players) will be defined in platform types. When the game designer design the message for players, he would select the platform characteristics/instructions he wants the player to enter, and when he design the message for the umpires, he selects other characteristics related to the status. 
I don't think message templates should be the place where the game designer defines the content of a specific game, as messages can be re-used across games.

**Comment by clenoble** [comment]
In platform types, we can have 2 sets of schema editor instead of one. One data schema for umpires to fill-in, one data schema for player to fill-in. Is that what you meant by messages?
Each of these data scheme could be then included in a message template. 
I think the misunderstanding comes from using message or message template as schema definition.

**Comment by clenoble** [comment]
Does the new layout with 2 schema editors correspond to what you expected? https://xd.adobe.com/view/1ee5edce-fac4-43f5-6f70-b48f49d52ed3-68d4/screen/3f504720-dd92-49b0-807e-73e5b2c39f3b/SERGE-Game-Platforms-1

**Comment by IanMayo** [comment]
Yes. There _may_ be a way to present the information in a more compact way.

One observation from playing with these schema editors is that the editor frequently consumes a lot more space than the preview.  Here's an example:

![image](https://user-images.githubusercontent.com/1108513/54743919-7841ef80-4bbd-11e9-996c-c65772e5a9c4.png)

As you'll see, we're only seeing 1/2 of the schema definition, but the preview only occupies a single line.

It would be great if the UI didn't fall beneath the visible area.  One route to to this is to put `Demanded` and `Actual` onto two tabs.  But, another route could be to arrange them horizontally. So, on each side we have a schema editor consuming 2/3 of the vertical space, and the preview occupying 1/3 of the space.

**Comment by clenoble** [comment]
I made different versions of the platform types UI to see how best to fit everything into one screen: [Platform Types wireframes](https://xd.adobe.com/view/d2a22612-da7b-45a4-63e8-33cb412d1e3d-a493/)
Having multiple scrollbars usually results in a bad UX. Users scroll areas involuntarily depending on where the focus is. Users actually don't mind scrolling if the content justifies it, but it's much easier when there is only the main window scrollbar.

**Comment by IanMayo** [comment]
Closing - sorted.
