### ISSUE TITLE
Game Design "Overview" settings page

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#18]
In the distant future, the clients wish to be able to support alternate turn strategies, including cycling through the forces:
* 30 mins for Blue to plan
* 30 mins for red to plan
* 30 mins for White to execute

In the future the `Overview` page will need to support Turn strategy.  We could represent this as a disabled `Turn Strategy` drop-down, labelled with `Not implemented`.

(fortunately) we don't expect to support this in any of the early phases.

**Comment by clenoble** [comment]
I'll add this disabled dropdown to the Overview page.
