### ISSUE TITLE
Channel Design process

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#19]
I invited the two users to talk through what they thought would be required to provide in order to create a channel.

They started with `Force`, and the less-tech-savvy of the two clients jumped straight in with identifying `Roles` within those forces too.   

(Note: this reinforces the feeling that `Role` is a suitable name.  When asked for examples of roles the game designer used `International Engagement` and `Blue Force Communications` - with the expectation that these would be performed by people at separate PCs).

(Note 2: I was a little nervous that a having a large number of channels may not be a real requirement - and it was just my logical extrapolation of the data.  But, the two designers said it wouldn't be unimaginable to have 8 channels open for that role - highlighting the importance of some flags/warning indicators for messages received in other channels/tabs).

Some channels may just have `General` messages.  But, the game designers were clear that the more structured the data was, the easier it would be to subsequently analyse it.  So, it's in their interest to provide dedicated message types, when possible.

**Comment by clenoble** [comment]
- In the player UI, I will make sure that channels with unread messages will be highlighted.
- I understand the need for subsequent analysis very well. Structured data can be provided by different message types, but what about the possibility to tag or categorize each message according to their contents, rather than their form? For example, a message could be marked "urgent", and triggers a specific highlight in the corresponding channel.

**Comment by IanMayo** [comment]
For the infrequent players, I don't think we can rely on them using the correct tags.  

I'm picturing a large "New" button at the top of the window for a channel.  Hopefully, in the list that gets shown there will be 2-5 message types, and their meaning is unambiguous. 

Frequently different message types will include different structures, and not just one large comment box.

So, for "Request Weather Forecast" I picture the data components being broken down like this:
https://rawgit.com/json-editor/json-editor/master/docs/demo.html?schema=N4IgLgngDgpiBcID2AjAVjAxmEAaEUATkrIWAJYwDOCoACjIeUgCa3jRyJVhMB2AczwgW1TEygUkfBCABqAQwA25FuUgACJADMN2pISwKewmHwCuAWwQBtEAEYATBoASSc4Rr5HAFlfvPYR8ADn8PLxAAdmc3cJAAXQBffAAlBTVzGnhQSFhZC0sURmFRKnFySWYZRDSMqi1dTCQAN0YFARgNAAoAOUsASmFLcj5ySysEAAZ8SwUADzGJ+HtJ6ZAzJZsAVlwV3C3pgE5JpPwAYTNeLhzOWVQMbBKxCSlqkAu+K4a9AyMeDUMAiquA0mRgLA0KAgGksMDAMAMSCUSCBJnwhgAjuZyIY2PA7AAZBQ4fAE6RCeL4IgkRgUajsIk4bIcPKIApFQggZIgMmCdi5LggdnFRLc/SEWZMkACJhsbkpGDGaT827cXgjIT4UrlSrKxAAdQAFtCFD9DJhjGANOR6kUNQCYFjqPC2PhxZLZPC5mAFIYFFzuRQwEpBQAxX4W/4Kp1okCY7G42wgBhMVjCWrkTLCD5XdOKqjKpJAA=&value=N4IgCgpgTglg9gExALhARgEwAIAScCuUAziADQgBKAhgjPicgKzkDCEAdgC5QQqgAyVTigAM5fnHYBzUQF9yFCFSKSUIELKA&lib_switcher=&prompt_before_delete&upload=function(a,b,c){console.log(%22Upload%20handler%20required%20for%20upload%20editor%22)}&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction

**Comment by clenoble** [comment]
I understand each message type will have a different structure, which is the reason for the message template editor, and that an advanced search interface will be able to filter by the content of specific fields. My suggestion of using tags was to introduce additional metadata, to differentiate messages within the same message type, or to search around a theme across different message types.
Maybe too complex for a v1 anyway.

**Comment by IanMayo** [comment]
Close - sorted.
