### ISSUE TITLE
Question. Force Objectives

### ISSUE THREAD

**Issue by IanMayo** [serge-web/serge-legacy#24]
The Force Objectives statements form an important part of the game. They're the objectives each player/team has to work towards, and also represent success/failure for that team, or the tactics employed by that team.

So, they need to be readily available.  Players don't need to edit them, but they do quickly need to be able to retrieve & read them.

While the objectives may change during a game, they don't change for each time step.

So, I _think_ they may be applicable in the *Turn state* and *Global communications* area of the UI. _Maybe_ some icon beneath the time label.

I've just googled `objectives icon` and got a range of dartboards & checklists:
https://www.google.co.uk/search?q=objectives+icon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiFh-Haqq_hAhVRSxUIHZjqD7IQ_AUIDigB&biw=1424&bih=1047

Here's an arrow in a target icon, in Font-Awesome:
https://fontawesome.com/icons/bullseye-arrow?style=solid

**Comment by clenoble** [comment]
Here is a suggestion: https://xd.adobe.com/view/d7896f40-3024-4414-7d45-1bd097e3b534-a1b8/screen/cebb5dcf-daab-4c0c-baa6-8ebe6a1941d3/SERGE-layout-A-1-3

I place the name of the force and the icon in the bottom right corner, under the Global OOG messages panel. Clicking on it opens a pop-up with the force objectives. Changes in objectives could be mentioned by a change in icon state (color / warning sign / animation)

(I used a bullseye icon without an arrow, as the one you selected requires a pro license on FontAwesome.)

**Comment by clenoble** [comment]
Text, icon and popup border would use the force designated color.

**Comment by IanMayo** [comment]
Close - sorted.
